application: gae-group-project
version: 3
runtime: php55
api_version: 1

handlers:

- url: /product-images
  static_dir: product-images

- url: /styles
  static_dir: styles

- url: /.*
  script: index.php